import { useState, useEffect, useMemo, useRef } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { useHotkeys } from '@/hooks/use-hotkeys'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { DescriptionTextarea } from '@/components/ui/description-textarea'
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxEmpty,
} from '@/components/ui/combobox'
import { HugeiconsIcon } from '@hugeicons/react'
import { TaskAdd01Icon, Folder01Icon, Cancel01Icon, Attachment01Icon, Link01Icon, Add01Icon, Tick01Icon, PinIcon, PinOffIcon } from '@hugeicons/core-free-icons'
import { cn } from '@/lib/utils'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { getTaskTypeCssVar } from '@/lib/task-type-colors'
import { Switch } from '@/components/ui/switch'
import { useCreateTask, useAddTaskLink } from '@/hooks/use-tasks'
import { useSearchTags } from '@/hooks/use-tags'
import type { TagWithUsage, RecurrenceRule, TaskPriority } from '@shared/types'
import { useBranches, checkIsGitRepo } from '@/hooks/use-filesystem'
import { useWorktreeBasePath, useScratchBasePath, useDefaultGitReposDir, useDefaultAgent, useOpencodeModel, useDefaultTaskType, useStartWorktreeTasksImmediately } from '@/hooks/use-config'
import { AGENT_DISPLAY_NAMES, type AgentType } from '@/types'
import { useRepositories } from '@/hooks/use-repositories'
import { useProjects } from '@/hooks/use-projects'
import { FilesystemBrowser } from '@/components/ui/filesystem-browser'
import { DatePickerPopover } from '@/components/ui/date-picker-popover'
import { ModelPicker } from '@/components/opencode/model-picker'
import { useUploadAttachment } from '@/hooks/use-task-attachments'
import { DependencySelector } from '@/components/kanban/dependency-selector'
import { TimeEstimatePicker } from '@/components/task/time-estimate-picker'
import { PriorityPicker } from '@/components/task/priority-picker'

type TaskType = 'worktree' | 'manual' | 'scratch'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function generateBranchName(text: string): string {
  // Take only the first 4 words to keep worktree paths short
  const words = text.trim().split(/\s+/).slice(0, 4).join(' ')
  const slug = slugify(words)
  if (!slug) return ''
  const suffix = Math.random().toString(36).substring(2, 6)
  return `${slug}-${suffix}`
}

// Common fields needed for task creation from a repository
interface DefaultRepositoryProps {
  id: string
  path: string
  displayName: string
  startupScript?: string | null
  copyFiles?: string | null
  defaultAgent?: AgentType | null
  claudeOptions?: Record<string, string> | null
  opencodeOptions?: Record<string, string> | null
  opencodeModel?: string | null
}

interface CreateTaskModalProps {
  open?: boolean
  onOpenChange?: (open: boolean) => void
  defaultRepository?: DefaultRepositoryProps
  showTrigger?: boolean
}

export function CreateTaskModal({ open: controlledOpen, onOpenChange, defaultRepository, showTrigger = true }: CreateTaskModalProps = {}) {
  const { t } = useTranslation('tasks')
  const { t: tc } = useTranslation('common')
  const [internalOpen, setInternalOpen] = useState(false)

  // Support both controlled and uncontrolled modes
  const open = controlledOpen ?? internalOpen
  const setOpen = onOpenChange ?? setInternalOpen
  const [browserOpen, setBrowserOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [taskType, setTaskType] = useState<TaskType>('worktree')
  const [startImmediately, setStartImmediately] = useState(true)
  const [tags, setTags] = useState<string[]>([])
  const [tagInput, setTagInput] = useState('')
  const [dueDate, setDueDate] = useState('')
  const [timeEstimate, setTimeEstimate] = useState<number | null>(null)
  const [priority, setPriority] = useState<TaskPriority>('medium')
  const [recurrenceRule, setRecurrenceRule] = useState<RecurrenceRule | ''>('')
  const [notes, setNotes] = useState('')
  const [repoPath, setRepoPath] = useState('')
  const [baseBranch, setBaseBranch] = useState('')
  const [branchSearchQuery, setBranchSearchQuery] = useState('')
  const [branch, setBranch] = useState('')
  const [autoGeneratedBranch, setAutoGeneratedBranch] = useState('')
  const [prefix, setPrefix] = useState('')
  const [aiMode, setAiMode] = useState<'default' | 'plan'>('default')
  const [aiModeManuallySet, setAiModeManuallySet] = useState(false)
  const [agent, setAgent] = useState<AgentType>('claude')
  const [selectedRepoId, setSelectedRepoId] = useState<string | null>(null)
  const [repoTab, setRepoTab] = useState<'saved' | 'browse'>('browse')
  const [repoSearchQuery, setRepoSearchQuery] = useState('')
  const [repoError, setRepoError] = useState<string | null>(null)
  const [isValidatingRepo, setIsValidatingRepo] = useState(false)
  const [opencodeModel, setOpencodeModel] = useState<string | null>(null)
  const [pendingFiles, setPendingFiles] = useState<File[]>([])
  const [pendingLinks, setPendingLinks] = useState<Array<{ url: string; label?: string }>>([])
  const [linkUrlInput, setLinkUrlInput] = useState('')
  const [linkLabelInput, setLinkLabelInput] = useState('')
  const [prUrl, setPrUrl] = useState('')
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null)
  const [blockedByTaskIds, setBlockedByTaskIds] = useState<string[]>([])
  const [showTagDropdown, setShowTagDropdown] = useState(false)
  const [projectSearchQuery, setProjectSearchQuery] = useState('')
  const [showProjectDropdown, setShowProjectDropdown] = useState(false)
  const [pinned, setPinned] = useState(false)
  const tagContainerRef = useRef<HTMLDivElement>(null)
  const projectContainerRef = useRef<HTMLDivElement>(null)

  const navigate = useNavigate()
  const createTask = useCreateTask()
  const uploadAttachment = useUploadAttachment()
  const addTaskLink = useAddTaskLink()
  const formRef = useRef<HTMLFormElement>(null)
  const attachmentInputRef = useRef<HTMLInputElement>(null)
  const { data: worktreeBasePath } = useWorktreeBasePath()
  const { data: scratchBasePath } = useScratchBasePath()
  const { data: defaultGitReposDir } = useDefaultGitReposDir()
  const { data: defaultAgent } = useDefaultAgent()
  const { data: globalOpencodeModel } = useOpencodeModel()
  const { data: defaultTaskType } = useDefaultTaskType()
  const { data: defaultStartImmediately } = useStartWorktreeTasksImmediately()
  const { data: repositories } = useRepositories()
  const { data: projects } = useProjects()
  const { data: branchData, isLoading: branchesLoading } = useBranches(
    repoPath || null
  )

  // Get the selected repository object
  const selectedRepo = selectedRepoId ? repositories?.find((r) => r.id === selectedRepoId) : null

  // Find the project that contains the selected repository (for config fallback)
  const selectedRepoProject = useMemo(() => {
    if (!selectedRepoId || !projects) return null
    return projects.find((p) => p.repositories.some((r) => r.id === selectedRepoId)) ?? null
  }, [selectedRepoId, projects])

  // Search for existing tags
  const { data: tagSearchResults = [] } = useSearchTags(tagInput)

  // Filter out already added tags
  const availableTags = tagSearchResults.filter(
    (result) => !tags.includes(result.name)
  )

  // Check for exact tag match
  const exactTagMatch = tagSearchResults.find(
    (t) => t.name.toLowerCase() === tagInput.toLowerCase()
  )
  const showCreateTagOption = tagInput.trim() && !exactTagMatch && !tags.includes(tagInput.trim())

  // Filter projects based on search query (for manual tasks)
  const filteredProjects = useMemo(() => {
    if (!projects) return []
    if (!projectSearchQuery.trim()) return projects
    const query = projectSearchQuery.toLowerCase()
    return projects.filter((p) => p.name.toLowerCase().includes(query))
  }, [projects, projectSearchQuery])

  // Filter repositories based on search query (case-insensitive fuzzy match)
  const filteredRepositories = useMemo(() => {
    if (!repositories) return []
    // Don't filter when a repo is selected and the query matches its display name
    // This ensures all repos are shown in the dropdown when the modal opens
    if (selectedRepo && repoSearchQuery === selectedRepo.displayName) {
      return repositories
    }
    if (!repoSearchQuery.trim()) return repositories
    const query = repoSearchQuery.toLowerCase()
    return repositories.filter((repo) =>
      repo.displayName.toLowerCase().includes(query) ||
      repo.path.toLowerCase().includes(query)
    )
  }, [repositories, repoSearchQuery, selectedRepo])

  const filteredBranches = useMemo(() => {
    if (!branchData?.branches) return []
    if (!branchSearchQuery.trim() || branchSearchQuery === baseBranch) return branchData.branches
    const query = branchSearchQuery.toLowerCase()
    return branchData.branches.filter((b) => b.toLowerCase().includes(query))
  }, [branchData?.branches, branchSearchQuery, baseBranch])

  // Set default tab based on whether repositories exist
  useEffect(() => {
    if (repositories && repositories.length > 0) {
      setRepoTab('saved')
    } else {
      setRepoTab('browse')
    }
  }, [repositories])

  // Initialize with default repository when modal opens, or auto-select most recently used
  useEffect(() => {
    if (open) {
      // Set task defaults from settings
      if (defaultTaskType) {
        setTaskType(defaultTaskType)
      }
      if (defaultStartImmediately !== undefined) {
        setStartImmediately(defaultStartImmediately)
      }

      // Determine which repository will be selected
      const selectedRepo = defaultRepository ?? (repositories && repositories.length > 0 ? repositories[0] : null)

      // Find the project for this repository (for config fallback)
      const repoProject = selectedRepo && projects
        ? projects.find((p) => p.repositories.some((r) => r.id === selectedRepo.id))
        : null

      // Set agent priority: repo -> project -> global -> 'claude'
      if (selectedRepo?.defaultAgent) {
        setAgent(selectedRepo.defaultAgent)
      } else if (repoProject?.defaultAgent) {
        setAgent(repoProject.defaultAgent)
      } else if (defaultAgent) {
        setAgent(defaultAgent)
      }

      // Set OpenCode model: repo -> project -> global -> null
      if (selectedRepo?.opencodeModel) {
        setOpencodeModel(selectedRepo.opencodeModel)
      } else if (repoProject?.opencodeModel) {
        setOpencodeModel(repoProject.opencodeModel)
      } else if (globalOpencodeModel) {
        setOpencodeModel(globalOpencodeModel)
      } else {
        setOpencodeModel(null)
      }

      if (defaultRepository) {
        // Use provided default repository
        setSelectedRepoId(defaultRepository.id)
        setRepoPath(defaultRepository.path)
        setRepoSearchQuery(defaultRepository.displayName)
        setRepoTab('saved')
      } else if (repositories && repositories.length > 0) {
        // Auto-select first repository (most recently used due to sorting)
        const firstRepo = repositories[0]
        setSelectedRepoId(firstRepo.id)
        setRepoPath(firstRepo.path)
        setRepoSearchQuery(firstRepo.displayName)
        setRepoTab('saved')
      }
    }
  }, [open, defaultRepository, repositories, projects, defaultAgent, globalOpencodeModel, defaultTaskType, defaultStartImmediately])

  // Set default base branch when branches are loaded, reset when repo changes
  useEffect(() => {
    if (branchData) {
      const repo = repositories?.find(r => r.id === selectedRepoId)
      const preferred = repo?.lastBaseBranch
      const branch = preferred && branchData.branches.includes(preferred)
        ? preferred
        : branchData.defaultBranch || branchData.branches[0] || 'main'
      setBaseBranch(branch)
      setBranchSearchQuery(branch)
    } else {
      setBaseBranch('')
      setBranchSearchQuery('')
    }
  }, [branchData, repoPath, repositories, selectedRepoId])

  // Close tag dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (tagContainerRef.current && !tagContainerRef.current.contains(e.target as Node)) {
        setShowTagDropdown(false)
      }
      if (projectContainerRef.current && !projectContainerRef.current.contains(e.target as Node)) {
        setShowProjectDropdown(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  const handleTitleChange = (value: string) => {
    setTitle(value)
    // Generate a new auto-generated branch name when title changes
    setAutoGeneratedBranch(generateBranchName(value))
  }

  const handleRepoSelect = async (path: string) => {
    setRepoError(null)
    setIsValidatingRepo(true)

    try {
      const result = await checkIsGitRepo(path)

      if (!result.isGitRepo) {
        setRepoError(t('createModal.errors.notGitRepo'))
        setIsValidatingRepo(false)
        return
      }

      // Valid git repo - set the path
      setRepoPath(path)

      // Check if this path matches an existing saved repository
      const existingRepo = repositories?.find((r) => r.path === path)
      if (existingRepo) {
        // Use the existing repo's settings (copyFiles, startupScript, etc.)
        setSelectedRepoId(existingRepo.id)
      } else {
        // No saved repo found - task will work but without saved settings
        // User can create a project to save repository settings
        setSelectedRepoId(null)
      }
    } catch (err) {
      setRepoError(err instanceof Error ? err.message : t('createModal.errors.validationFailed'))
    } finally {
      setIsValidatingRepo(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!title.trim()) return

    // For code tasks, repo is required
    if (taskType === 'worktree' && !repoPath) return

    // Build the task payload based on type
    const isCodeTask = taskType === 'worktree'
    const isScratch = taskType === 'scratch'
    // Code tasks that don't start immediately go to TO_DO and don't create worktree yet
    const shouldStartWork = isCodeTask && startImmediately
    const shouldStartScratch = isScratch && startImmediately

    // Code task specific fields - only set when starting work immediately
    const repoName = shouldStartWork ? (repoPath.split('/').pop() || 'repo') : null
    const rawBranchForSubmit = shouldStartWork ? (branch.trim() || autoGeneratedBranch) : null
    const prefixedBranch = shouldStartWork && rawBranchForSubmit
      ? (prefix.trim() ? `${prefix.trim().replace(/\/+$/, '')}/${rawBranchForSubmit}` : rawBranchForSubmit)
      : null
    const worktreePath = shouldStartWork && prefixedBranch ? `${worktreeBasePath}/${prefixedBranch}` : null

    // Standalone task specific fields
    const scratchSlug = slugify(title.trim().split(/\s+/).slice(0, 4).join(' '))
    const scratchSuffix = Math.random().toString(36).substring(2, 6)
    const scratchDirName = scratchSlug ? `${scratchSlug}-${scratchSuffix}` : scratchSuffix
    const scratchPath = shouldStartScratch ? `${scratchBasePath}/${scratchDirName}` : null

    // Select the appropriate agent options: repo -> project -> (global is handled by backend)
    const agentOptions = agent === 'claude'
      ? (selectedRepo?.claudeOptions ?? selectedRepoProject?.claudeOptions)
      : (selectedRepo?.opencodeOptions ?? selectedRepoProject?.opencodeOptions)

    createTask.mutate(
      {
        title: title.trim(),
        description: description.trim() || undefined,
        status: (shouldStartWork || shouldStartScratch) ? 'IN_PROGRESS' : 'TO_DO',
        agent,
        aiMode: (isCodeTask || isScratch) ? aiMode : undefined,
        // Git fields - only fully populated when starting work immediately
        repoPath: shouldStartWork ? repoPath : null,
        repoName: shouldStartWork ? repoName : null,
        baseBranch: isCodeTask ? (baseBranch || 'main') : null,
        branch: shouldStartWork ? prefixedBranch : null,
        prefix: isCodeTask && prefix.trim() ? prefix.trim() : undefined,
        worktreePath: shouldStartWork ? worktreePath : (shouldStartScratch ? scratchPath : null),
        // Type field for scratch tasks
        type: isScratch ? 'scratch' : (isCodeTask ? 'worktree' : undefined),
        // Repository reference for deferred worktree creation
        repositoryId: isCodeTask && !startImmediately ? selectedRepoId : undefined,
        copyFiles: isCodeTask ? (selectedRepo?.copyFiles || undefined) : undefined,
        startupScript: isCodeTask ? (selectedRepo?.startupScript || undefined) : undefined,
        agentOptions: (isCodeTask || isScratch) ? (agentOptions || undefined) : undefined,
        opencodeModel: (isCodeTask || isScratch) && agent === 'opencode' ? opencodeModel : undefined,
        // Generalized task fields
        tags: tags.length > 0 ? tags : undefined,
        dueDate: dueDate || null,
        timeEstimate: timeEstimate,
        priority: priority,
        recurrenceRule: recurrenceRule || null,
        notes: notes.trim() || null,
        projectId: isCodeTask ? selectedRepoProject?.id : selectedProjectId,
        prUrl: prUrl.trim() || null,
        // Dependencies
        blockedByTaskIds: blockedByTaskIds.length > 0 ? blockedByTaskIds : undefined,
        // Pin
        pinned: pinned || undefined,
      },
      {
        onSuccess: async (task) => {
          // Upload any pending attachments
          if (pendingFiles.length > 0) {
            for (const file of pendingFiles) {
              try {
                await uploadAttachment.mutateAsync({ taskId: task.id, file })
              } catch {
                // Continue with other files even if one fails
              }
            }
          }

          // Add any pending links
          if (pendingLinks.length > 0) {
            for (const link of pendingLinks) {
              try {
                await addTaskLink.mutateAsync({ taskId: task.id, url: link.url, label: link.label })
              } catch {
                // Continue with other links even if one fails
              }
            }
          }

          setOpen(false)
          resetForm()

          // Navigate to task detail page when starting work immediately
          if (shouldStartWork || shouldStartScratch) {
            const navState = description.trim()
              ? { aiMode, description: description.trim(), focusTerminal: true }
              : { aiMode, focusTerminal: true }
            navigate({ to: '/tasks/$taskId', params: { taskId: task.id }, state: navState as Record<string, unknown> })
          }
        },
        onError: (error) => {
          toast.error(t('createModal.errors.createFailed'), {
            description: error instanceof Error ? error.message : String(error),
          })
        },
      }
    )
  }

  const resetForm = () => {
    setTitle('')
    setDescription('')
    setTaskType('worktree')
    setStartImmediately(true)
    setTags([])
    setTagInput('')
    setDueDate('')
    setTimeEstimate(null)
    setPriority('medium')
    setRecurrenceRule('')
    setNotes('')
    setPendingFiles([])
    setPendingLinks([])
    setLinkUrlInput('')
    setLinkLabelInput('')
    setPrUrl('')
    setRepoPath('')
    setBaseBranch('')
    setBranch('')
    setAutoGeneratedBranch('')
    setPrefix('')
    setAiMode('default')
    setAiModeManuallySet(false)
    setAgent(defaultAgent || 'claude')
    setOpencodeModel(null)
    setSelectedRepoId(null)
    setRepoSearchQuery('')
    setRepoError(null)
    setSelectedProjectId(null)
    setBlockedByTaskIds([])
    setPinned(false)
    setShowTagDropdown(false)
    setProjectSearchQuery('')
    setShowProjectDropdown(false)
    // Reset tab to saved if repositories exist, otherwise browse
    setRepoTab(repositories && repositories.length > 0 ? 'saved' : 'browse')
  }

  const handleAddTag = (tagName?: string) => {
    const trimmed = (tagName ?? tagInput).trim()
    if (trimmed && !tags.includes(trimmed)) {
      setTags([...tags, trimmed])
    }
    setTagInput('')
    setShowTagDropdown(false)
  }

  const handleRemoveTag = (tag: string) => {
    setTags(tags.filter((t) => t !== tag))
  }

  const handleTagKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && tagInput.trim()) {
      e.preventDefault()
      // Add exact match if available, otherwise create new tag
      if (exactTagMatch && !tags.includes(exactTagMatch.name)) {
        handleAddTag(exactTagMatch.name)
      } else if (showCreateTagOption) {
        handleAddTag(tagInput.trim())
      }
    } else if (e.key === 'Escape') {
      setShowTagDropdown(false)
      setTagInput('')
    } else if (e.key === 'Backspace' && !tagInput && tags.length > 0) {
      // Remove last tag on backspace when input is empty
      setTags(tags.slice(0, -1))
    }
  }

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (!files) return
    setPendingFiles(prev => [...prev, ...Array.from(files)])
    // Reset input so the same file can be selected again
    e.target.value = ''
  }

  const handleRemoveFile = (index: number) => {
    setPendingFiles(prev => prev.filter((_, i) => i !== index))
  }

  const handleAddLink = () => {
    const trimmedUrl = linkUrlInput.trim()
    if (!trimmedUrl) return

    // Validate URL format
    try {
      new URL(trimmedUrl)
    } catch {
      toast.error(t('createModal.errors.invalidUrl'), {
        description: t('createModal.errors.invalidUrlDescription'),
      })
      return
    }

    setPendingLinks(prev => [...prev, { url: trimmedUrl, label: linkLabelInput.trim() || undefined }])
    setLinkUrlInput('')
    setLinkLabelInput('')
  }

  const handleRemoveLink = (index: number) => {
    setPendingLinks(prev => prev.filter((_, i) => i !== index))
  }

  const handleLinkKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault()
      handleAddLink()
    }
  }

  // Cmd+Enter to submit form when modal is open
  const canSubmit = !createTask.isPending && !!title.trim() && (taskType === 'manual' || taskType === 'scratch' || !!repoPath)
  useHotkeys('meta+enter', () => {
    if (formRef.current) {
      formRef.current.requestSubmit()
    }
  }, {
    enabled: open && canSubmit,
    allowInInput: true,
    ignoreContext: true,
    deps: [open, canSubmit],
  })

  const rawBranch = branch.trim() || autoGeneratedBranch
  const effectiveBranch = prefix.trim() && rawBranch ? `${prefix.trim().replace(/\/+$/, '')}/${rawBranch}` : rawBranch
  const displayWorktreePath = effectiveBranch
    ? `${worktreeBasePath}/${effectiveBranch}`
    : ''

  return (
    <>
      <Dialog open={open} onOpenChange={setOpen}>
        {showTrigger && (
          <DialogTrigger render={<Button size="sm" />}>
            <HugeiconsIcon icon={TaskAdd01Icon} size={16} strokeWidth={2} data-slot="icon" className="-translate-y-px" />
            {t('newTask')}
          </DialogTrigger>
        )}
        <DialogContent className="sm:max-w-md max-h-[80dvh] flex flex-col overflow-hidden">
          <form ref={formRef} onSubmit={handleSubmit} className="flex flex-col min-h-0 flex-1">
            <DialogHeader className="shrink-0 px-3">
              <DialogTitle className="sr-only">{t('createModal.title')}</DialogTitle>
              <ToggleGroup
                value={[taskType]}
                onValueChange={(value) => {
                  const selected = Array.isArray(value) ? value[0] : value
                  if (selected) {
                    setTaskType(selected as TaskType)
                    if (selected !== 'manual') setRecurrenceRule('')
                  }
                }}
                className="h-7 mx-auto"
                variant="outline"
              >
                {(['worktree', 'scratch', 'manual'] as const).map((type) => (
                  <ToggleGroupItem
                    key={type}
                    value={type}
                    className="h-7 rounded-full px-3 text-xs font-medium"
                    style={taskType === type ? { backgroundColor: getTaskTypeCssVar({ type }), color: 'white' } : undefined}
                  >
                    {t(`createModal.taskTypes.${type}`)}
                  </ToggleGroupItem>
                ))}
              </ToggleGroup>
              <DialogDescription className="mt-2 text-center">
                {taskType === 'worktree'
                  ? t('createModal.taskDescriptions.worktree')
                  : taskType === 'scratch'
                    ? t('createModal.taskDescriptions.scratch')
                    : t('createModal.taskDescriptions.manual')}
              </DialogDescription>
            </DialogHeader>

            <FieldGroup className="mt-2 py-4 px-3 overflow-y-auto min-h-0 flex-1">
              <Field>
                <FieldLabel htmlFor="title">{t('createModal.fields.title')}</FieldLabel>
                <div className="flex gap-1.5 items-center">
                  <Input
                    id="title"
                    value={title}
                    onChange={(e) => handleTitleChange(e.target.value)}
                    placeholder={t('createModal.fields.titlePlaceholder')}
                    required
                    autoFocus
                    className="flex-1"
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon-sm"
                    className={cn(
                      'shrink-0 cursor-pointer',
                      pinned ? 'text-primary' : 'text-muted-foreground hover:text-foreground'
                    )}
                    onClick={() => setPinned(!pinned)}
                    title={pinned ? t('createModal.unpinTask') : t('createModal.pinTask')}
                  >
                    <HugeiconsIcon icon={pinned ? PinOffIcon : PinIcon} size={16} strokeWidth={2} />
                  </Button>
                </div>
              </Field>

              <Field>
                <FieldLabel htmlFor="description">{t('createModal.fields.description')}</FieldLabel>
                <DescriptionTextarea
                  id="description"
                  value={description}
                  onValueChange={(value) => {
                    setDescription(value)
                    // Auto-switch AI mode based on description content (unless manually set)
                    if (!aiModeManuallySet && (taskType === 'worktree' || taskType === 'scratch')) {
                      setAiMode(value.trim() ? 'plan' : 'default')
                    }
                  }}
                  placeholder={t('createModal.fields.descriptionPlaceholder')}
                  rows={2}
                />
              </Field>

              {/* AI Mode - for worktree and scratch tasks */}
              {(taskType === 'worktree' || taskType === 'scratch') && (
                <Field>
                  <FieldLabel>{t('createModal.fields.aiMode')}</FieldLabel>
                  <ToggleGroup
                    value={[aiMode]}
                    onValueChange={(value) => {
                      const selected = Array.isArray(value) ? value[0] : value
                      if (selected) {
                        setAiMode(selected as 'default' | 'plan')
                        setAiModeManuallySet(true)
                      }
                    }}
                    className="w-full"
                    variant="outline"
                  >
                    <ToggleGroupItem value="plan" className="flex-1">{t('createModal.aiModes.plan')}</ToggleGroupItem>
                    <ToggleGroupItem value="default" className="flex-1">{t('createModal.aiModes.default')}</ToggleGroupItem>
                  </ToggleGroup>
                </Field>
              )}

              {/* Project selector for manual and scratch tasks */}
              {(taskType === 'manual' || taskType === 'scratch') && (
                <Field>
                  <FieldLabel>{t('createModal.fields.project')}</FieldLabel>
                  <div className="relative" ref={projectContainerRef}>
                    <Input
                      value={selectedProjectId
                        ? projects?.find((p) => p.id === selectedProjectId)?.name || ''
                        : projectSearchQuery
                      }
                      onChange={(e) => {
                        setProjectSearchQuery(e.target.value)
                        setSelectedProjectId(null)
                        setShowProjectDropdown(true)
                      }}
                      onFocus={() => setShowProjectDropdown(true)}
                      onKeyDown={(e) => {
                        if (e.key === 'Escape') {
                          setShowProjectDropdown(false)
                        }
                      }}
                      placeholder={t('createModal.noProject')}
                      className="w-full"
                    />

                    {/* Project dropdown */}
                    {showProjectDropdown && (
                      <div className="absolute top-full left-0 right-0 mt-1 bg-popover border rounded-md shadow-lg z-50 max-h-48 overflow-y-auto">
                        <button
                          type="button"
                          className={cn(
                            'group w-full px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground flex items-center justify-between',
                            selectedProjectId === null && 'bg-accent text-accent-foreground'
                          )}
                          onClick={() => {
                            setSelectedProjectId(null)
                            setProjectSearchQuery('')
                            setShowProjectDropdown(false)
                          }}
                        >
                          <span className={cn(
                            'text-muted-foreground group-hover:text-accent-foreground',
                            selectedProjectId === null && 'text-accent-foreground'
                          )}>{t('createModal.noProject')}</span>
                          {selectedProjectId === null && (
                            <HugeiconsIcon icon={Tick01Icon} size={14} className="text-primary" />
                          )}
                        </button>
                        {filteredProjects.map((project) => (
                          <button
                            key={project.id}
                            type="button"
                            className={cn(
                              'group w-full px-3 py-2 text-left text-sm hover:bg-accent hover:text-accent-foreground flex items-center justify-between',
                              selectedProjectId === project.id && 'bg-accent text-accent-foreground'
                            )}
                            onClick={() => {
                              setSelectedProjectId(project.id)
                              setProjectSearchQuery('')
                              setShowProjectDropdown(false)
                            }}
                          >
                            <span>{project.name}</span>
                            <span className={cn(
                              'text-xs text-muted-foreground group-hover:text-accent-foreground',
                              selectedProjectId === project.id && 'text-accent-foreground'
                            )}>
                              {project.taskCount ?? 0} tasks
                            </span>
                          </button>
                        ))}
                        {filteredProjects.length === 0 && projectSearchQuery && (
                          <div className="px-3 py-2 text-sm text-muted-foreground">
                            No projects found
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                  <FieldDescription>
                    {t('createModal.projectHint')}
                  </FieldDescription>
                </Field>
              )}

              {/* Agent selector - for worktree and scratch tasks */}
              {(taskType === 'worktree' || taskType === 'scratch') && (
                <>
              <Field>
                <FieldLabel>{t('createModal.fields.agent')}</FieldLabel>
                <Select value={agent} onValueChange={(value) => setAgent(value as AgentType)}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(Object.keys(AGENT_DISPLAY_NAMES) as AgentType[]).map((agentType) => (
                      <SelectItem key={agentType} value={agentType}>
                        {AGENT_DISPLAY_NAMES[agentType]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>

              {agent === 'opencode' && (
                <Field>
                  <FieldLabel>{t('createModal.fields.opencodeModel')}</FieldLabel>
                  <ModelPicker
                    value={opencodeModel}
                    onChange={setOpencodeModel}
                    placeholder={t('createModal.fields.opencodeModelPlaceholder')}
                  />
                </Field>
              )}
                </>
              )}

              {/* Repository & branch - only for worktree tasks */}
              {taskType === 'worktree' && (
                <>
              <Field>
                <FieldLabel>{t('createModal.fields.repository')}</FieldLabel>
                <Tabs
                  value={repoTab}
                  onValueChange={(v) => {
                    setRepoTab(v as 'saved' | 'browse')
                    setRepoError(null)
                  }}
                >
                  <TabsList>
                    <TabsTrigger value="saved" disabled={!repositories?.length}>
                      {t('createModal.tabs.saved')}
                    </TabsTrigger>
                    <TabsTrigger value="browse">{t('createModal.tabs.browse')}</TabsTrigger>
                  </TabsList>

                  <TabsContent value="saved" className="mt-2">
                    <Combobox
                      value={selectedRepoId || ''}
                      onValueChange={(id) => {
                        const repo = repositories?.find((r) => r.id === id)
                        if (repo) {
                          setSelectedRepoId(id as string)
                          setRepoPath(repo.path)
                          setRepoSearchQuery(repo.displayName)
                          setRepoError(null)

                          // Find the project for this repository (for config fallback)
                          const repoProject = projects?.find((p) => p.repositories.some((r) => r.id === id))

                          // Update agent: repo -> project -> global
                          if (repo.defaultAgent) {
                            setAgent(repo.defaultAgent)
                          } else if (repoProject?.defaultAgent) {
                            setAgent(repoProject.defaultAgent)
                          }

                          // Update OpenCode model: repo -> project -> global
                          setOpencodeModel(repo.opencodeModel ?? repoProject?.opencodeModel ?? globalOpencodeModel ?? null)
                        }
                      }}
                      inputValue={repoSearchQuery}
                      onInputValueChange={(value) => {
                        setRepoSearchQuery(value)
                        // Don't clear selection when typing - user must explicitly select
                        // This ensures startupScript/copyFiles are preserved from the selected repo
                      }}
                      itemToStringLabel={(id) =>
                        repositories?.find((r) => r.id === id)?.displayName || ''
                      }
                    >
                      <ComboboxInput
                        placeholder={t('createModal.searchRepositories')}
                        className="w-full"
                      />
                      <ComboboxContent>
                        <ComboboxList>
                          <ComboboxEmpty>{t('createModal.noRepositoriesFound')}</ComboboxEmpty>
                          {filteredRepositories.map((repo) => (
                            <ComboboxItem key={repo.id} value={repo.id}>
                              {repo.displayName}
                            </ComboboxItem>
                          ))}
                        </ComboboxList>
                      </ComboboxContent>
                    </Combobox>
                  </TabsContent>

                  <TabsContent value="browse" className="mt-2">
                    <Button
                      type="button"
                      variant="outline"
                      className="w-full justify-start font-normal"
                      onClick={() => setBrowserOpen(true)}
                      disabled={isValidatingRepo}
                    >
                      <HugeiconsIcon
                        icon={Folder01Icon}
                        size={14}
                        strokeWidth={2}
                        className="mr-2"
                      />
                      {isValidatingRepo ? (
                        <span className="text-muted-foreground">{tc('status.validating')}</span>
                      ) : repoPath && !selectedRepoId ? (
                        <span className="truncate">{repoPath}</span>
                      ) : (
                        <span className="text-muted-foreground group-hover/button:text-accent-foreground">{t('createModal.selectFolder')}</span>
                      )}
                    </Button>
                  </TabsContent>
                </Tabs>

                {repoError && (
                  <p className="text-sm text-destructive">{repoError}</p>
                )}

                {repoPath && !repoError && (
                  <FieldDescription className="font-mono text-xs truncate">
                    {repoPath}
                  </FieldDescription>
                )}
              </Field>

              <Field>
                <FieldLabel htmlFor="baseBranch">{t('createModal.fields.baseBranch')}</FieldLabel>
                <Combobox
                  value={baseBranch}
                  onValueChange={(value) => {
                    setBaseBranch(value ?? '')
                    setBranchSearchQuery(value ?? '')
                  }}
                  inputValue={branchSearchQuery}
                  onInputValueChange={setBranchSearchQuery}
                  itemToStringLabel={(value) => value}
                >
                  <ComboboxInput
                    disabled={!repoPath || branchesLoading}
                    placeholder={
                      !repoPath
                        ? t('createModal.selectRepositoryFirst')
                        : branchesLoading
                        ? t('createModal.loadingBranches')
                        : t('createModal.selectBranch')
                    }
                    className="w-full"
                  />
                  <ComboboxContent>
                    <ComboboxList>
                      <ComboboxEmpty>{t('createModal.noBranchesFound')}</ComboboxEmpty>
                      {filteredBranches.map((b) => (
                        <ComboboxItem key={b} value={b}>
                          {b}
                          {b === branchData?.current && (
                            <span className="text-muted-foreground ml-2">{t('createModal.current')}</span>
                          )}
                        </ComboboxItem>
                      ))}
                    </ComboboxList>
                  </ComboboxContent>
                </Combobox>
              </Field>

              <Field>
                <FieldLabel htmlFor="prefix">{t('createModal.fields.prefix')}</FieldLabel>
                <Input
                  id="prefix"
                  value={prefix}
                  onChange={(e) => setPrefix(e.target.value)}
                  placeholder={t('createModal.fields.prefixPlaceholder')}
                />
                <FieldDescription>
                  {t('createModal.prefixHint')}
                </FieldDescription>
              </Field>

              <Field>
                <FieldLabel htmlFor="branch">{t('createModal.fields.branchName')}</FieldLabel>
                <Input
                  id="branch"
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                  placeholder={autoGeneratedBranch || t('createModal.fields.branchPlaceholder')}
                />
                {displayWorktreePath && (
                  <FieldDescription>
                    {t('createModal.worktreePrefix')} {displayWorktreePath}
                  </FieldDescription>
                )}
                {!branch.trim() && autoGeneratedBranch && (
                  <FieldDescription>
                    {t('createModal.branchAutoGenerated', { branch: autoGeneratedBranch })}
                  </FieldDescription>
                )}
              </Field>
                </>
              )}

              {/* Estimate */}
              <Field>
                <FieldLabel>{t('createModal.fields.estimate')}</FieldLabel>
                <TimeEstimatePicker value={timeEstimate} onChange={setTimeEstimate} />
              </Field>

              {/* Priority */}
              <Field>
                <FieldLabel>{t('createModal.fields.priority')}</FieldLabel>
                <PriorityPicker value={priority} onChange={(v) => setPriority(v ?? 'medium')} />
              </Field>

              {/* Tags and Due Date row - always at bottom */}
              <div className="flex gap-3">
                <Field className="flex-1">
                  <FieldLabel htmlFor="tags">{t('createModal.fields.tags')}</FieldLabel>
                  <div className="relative" ref={tagContainerRef}>
                    <div className="flex flex-wrap items-center gap-1 rounded-md border border-input bg-background px-2 py-1.5 min-h-[36px]">
                      {tags.map((tag) => (
                        <span
                          key={tag}
                          className="inline-flex items-center gap-0.5 rounded border border-border bg-card px-1.5 py-0.5 text-xs font-medium"
                        >
                          {tag}
                          <button
                            type="button"
                            onClick={() => handleRemoveTag(tag)}
                            className="text-muted-foreground hover:text-foreground"
                          >
                            <HugeiconsIcon icon={Cancel01Icon} size={10} />
                          </button>
                        </span>
                      ))}
                      <input
                        id="tags"
                        type="text"
                        value={tagInput}
                        onChange={(e) => {
                          setTagInput(e.target.value)
                          setShowTagDropdown(true)
                        }}
                        onFocus={() => setShowTagDropdown(true)}
                        onKeyDown={handleTagKeyDown}
                        placeholder={tags.length === 0 ? t('createModal.fields.tagsPlaceholder') : ''}
                        className="flex-1 min-w-[60px] bg-transparent text-sm outline-none placeholder:text-muted-foreground"
                      />
                    </div>

                    {/* Tag dropdown */}
                    {showTagDropdown && (tagInput || availableTags.length > 0) && (
                      <div className="absolute top-full left-0 right-0 mt-1 bg-popover border rounded-md shadow-lg z-50 max-h-48 overflow-y-auto">
                        {availableTags.map((tag: TagWithUsage) => (
                          <button
                            key={tag.id}
                            type="button"
                            className="w-full px-3 py-2 text-left text-sm hover:bg-accent flex items-center justify-between"
                            onClick={() => handleAddTag(tag.name)}
                          >
                            <span>{tag.name}</span>
                            <span className="text-xs text-muted-foreground">
                              {tag.taskCount + tag.projectCount} uses
                            </span>
                          </button>
                        ))}
                        {showCreateTagOption && (
                          <button
                            type="button"
                            className={cn(
                              'w-full px-3 py-2 text-left text-sm hover:bg-accent flex items-center gap-2',
                              availableTags.length > 0 && 'border-t'
                            )}
                            onClick={() => handleAddTag(tagInput.trim())}
                          >
                            <HugeiconsIcon icon={Add01Icon} size={14} />
                            <span>Create "{tagInput.trim()}"</span>
                          </button>
                        )}
                        {!showCreateTagOption && availableTags.length === 0 && tagInput && (
                          <div className="px-3 py-2 text-sm text-muted-foreground">
                            No matching tags
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </Field>

                <Field className="w-40">
                  <FieldLabel>{t('createModal.fields.dueDate')}</FieldLabel>
                  <DatePickerPopover
                    value={dueDate || null}
                    onChange={(date) => setDueDate(date || '')}
                    placeholder={t('createModal.fields.dueDatePlaceholder')}
                    showClear
                    className="border border-input rounded-md px-3 py-2 w-full justify-start"
                  />
                </Field>

                {taskType === 'manual' && (
                <Field className="w-32">
                  <FieldLabel>{t('createModal.fields.repeat')}</FieldLabel>
                  <Select
                    value={recurrenceRule || 'none'}
                    onValueChange={(value) => setRecurrenceRule(value === 'none' ? '' : value as RecurrenceRule)}
                  >
                    <SelectTrigger className="w-full !h-auto py-2">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">{t('createModal.recurrence.none')}</SelectItem>
                      <SelectItem value="daily">{t('createModal.recurrence.daily')}</SelectItem>
                      <SelectItem value="weekly">{t('createModal.recurrence.weekly')}</SelectItem>
                      <SelectItem value="biweekly">{t('createModal.recurrence.biweekly')}</SelectItem>
                      <SelectItem value="monthly">{t('createModal.recurrence.monthly')}</SelectItem>
                      <SelectItem value="quarterly">{t('createModal.recurrence.quarterly')}</SelectItem>
                      <SelectItem value="yearly">{t('createModal.recurrence.yearly')}</SelectItem>
                    </SelectContent>
                  </Select>
                </Field>
                )}
              </div>

              {/* Notes */}
              <Field>
                <FieldLabel htmlFor="notes">{t('createModal.fields.notes')}</FieldLabel>
                <textarea
                  id="notes"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder={t('createModal.fields.notesPlaceholder')}
                  rows={2}
                  className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring resize-none"
                />
              </Field>

              {/* Blocked By (Dependencies) */}
              <Field>
                <FieldLabel>{t('createModal.fields.blockedBy')}</FieldLabel>
                <DependencySelector
                  selectedIds={blockedByTaskIds}
                  onSelectionChange={setBlockedByTaskIds}
                />
                <FieldDescription>
                  {t('createModal.blockedByHint')}
                </FieldDescription>
              </Field>

              {/* Links */}
              <Field>
                <FieldLabel>{t('createModal.fields.links')}</FieldLabel>
                <div className="space-y-2">
                  {pendingLinks.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      {pendingLinks.map((link, index) => (
                        <span
                          key={`${link.url}-${index}`}
                          className="inline-flex items-center gap-1 rounded border border-border bg-card px-1.5 py-0.5 text-xs"
                        >
                          <HugeiconsIcon icon={Link01Icon} size={10} className="shrink-0" />
                          <span className="truncate max-w-[150px]">{link.label || link.url}</span>
                          <button
                            type="button"
                            onClick={() => handleRemoveLink(index)}
                            className="text-muted-foreground hover:text-foreground"
                          >
                            <HugeiconsIcon icon={Cancel01Icon} size={10} />
                          </button>
                        </span>
                      ))}
                    </div>
                  )}
                  <div className="flex gap-2">
                    <Input
                      type="url"
                      value={linkUrlInput}
                      onChange={(e) => setLinkUrlInput(e.target.value)}
                      onKeyDown={handleLinkKeyDown}
                      placeholder={t('createModal.fields.urlPlaceholder')}
                      className="flex-1 h-8 text-sm"
                    />
                    <Input
                      type="text"
                      value={linkLabelInput}
                      onChange={(e) => setLinkLabelInput(e.target.value)}
                      onKeyDown={handleLinkKeyDown}
                      placeholder={t('createModal.fields.linkLabelPlaceholder')}
                      className="w-28 h-8 text-sm"
                    />
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      className="h-8 px-2"
                      onClick={handleAddLink}
                      disabled={!linkUrlInput.trim()}
                    >
                      <HugeiconsIcon icon={Add01Icon} size={14} />
                    </Button>
                  </div>
                </div>
              </Field>

              {/* GitHub PR */}
              <Field>
                <FieldLabel>{t('createModal.fields.prUrl')}</FieldLabel>
                <Input
                  type="url"
                  value={prUrl}
                  onChange={(e) => setPrUrl(e.target.value)}
                  placeholder={t('createModal.fields.prUrlPlaceholder')}
                  className="h-8 text-sm"
                />
              </Field>

              {/* Attachments */}
              <Field>
                <FieldLabel>{t('createModal.fields.attachments')}</FieldLabel>
                <div className="space-y-2">
                  <input
                    ref={attachmentInputRef}
                    type="file"
                    multiple
                    className="hidden"
                    onChange={handleFileSelect}
                    accept=".pdf,.png,.jpg,.jpeg,.gif,.webp,.svg,.txt,.md,.doc,.docx,.xls,.xlsx,.csv"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="w-full justify-start text-muted-foreground"
                    onClick={() => attachmentInputRef.current?.click()}
                  >
                    <HugeiconsIcon icon={Attachment01Icon} size={14} className="mr-2" />
                    {pendingFiles.length === 0 ? t('createModal.fields.addAttachments') : t('createModal.fields.addMoreFiles')}
                  </Button>
                  {pendingFiles.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      {pendingFiles.map((file, index) => (
                        <span
                          key={`${file.name}-${index}`}
                          className="inline-flex items-center gap-0.5 rounded border border-border bg-card px-1.5 py-0.5 text-xs font-medium"
                        >
                          {file.name}
                          <button
                            type="button"
                            onClick={() => handleRemoveFile(index)}
                            className="text-muted-foreground hover:text-foreground"
                          >
                            <HugeiconsIcon icon={Cancel01Icon} size={10} />
                          </button>
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </Field>
            </FieldGroup>

            <DialogFooter className="mt-4 shrink-0 px-3">
              {(taskType === 'worktree' || taskType === 'scratch') && (
                <label className="flex items-center gap-2 mr-auto cursor-pointer">
                  <Switch
                    checked={startImmediately}
                    onCheckedChange={setStartImmediately}
                    size="sm"
                  />
                  <span className="text-sm text-muted-foreground">{t('createModal.startImmediately')}</span>
                </label>
              )}
              <DialogClose render={<Button variant="outline" type="button" className="border-destructive text-destructive hover:bg-destructive hover:text-white" />}>
                {tc('buttons.cancel')}
              </DialogClose>
              <Button
                type="submit"
                disabled={!canSubmit}
              >
                {createTask.isPending ? tc('status.creating') : t('createModal.createTask')}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <FilesystemBrowser
        open={browserOpen}
        onOpenChange={setBrowserOpen}
        onSelect={handleRepoSelect}
        initialPath={defaultGitReposDir || undefined}
      />
    </>
  )
}
