/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalsIndexRouteImport } from './routes/terminals/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as AssistantIndexRouteImport } from './routes/assistant/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as RepositoriesRepoIdRouteImport } from './routes/repositories/$repoId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalsIndexRoute = TerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepoIdRoute = RepositoriesRepoIdRouteImport.update({
  id: '/repositories/$repoId',
  path: '/repositories/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/apps': typeof AppsIndexRoute
  '/assistant': typeof AssistantIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/review': typeof ReviewIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/terminals': typeof TerminalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/apps': typeof AppsIndexRoute
  '/assistant': typeof AssistantIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/review': typeof ReviewIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/terminals': typeof TerminalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/apps/': typeof AppsIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/terminals/': typeof TerminalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/projects/$projectId'
    | '/repositories/$repoId'
    | '/tasks/$taskId'
    | '/apps'
    | '/assistant'
    | '/calendar'
    | '/jobs'
    | '/monitoring'
    | '/projects'
    | '/repositories'
    | '/review'
    | '/settings'
    | '/tasks'
    | '/terminals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/projects/$projectId'
    | '/repositories/$repoId'
    | '/tasks/$taskId'
    | '/apps'
    | '/assistant'
    | '/calendar'
    | '/jobs'
    | '/monitoring'
    | '/projects'
    | '/repositories'
    | '/review'
    | '/settings'
    | '/tasks'
    | '/terminals'
  id:
    | '__root__'
    | '/'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/projects/$projectId'
    | '/repositories/$repoId'
    | '/tasks/$taskId'
    | '/apps/'
    | '/assistant/'
    | '/calendar/'
    | '/jobs/'
    | '/monitoring/'
    | '/projects/'
    | '/repositories/'
    | '/review/'
    | '/settings/'
    | '/tasks/'
    | '/terminals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsNewRoute: typeof JobsNewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  RepositoriesRepoIdRoute: typeof RepositoriesRepoIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TerminalsIndexRoute: typeof TerminalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminals/': {
      id: '/terminals/'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repoId': {
      id: '/repositories/$repoId'
      path: '/repositories/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof RepositoriesRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsNewRoute: JobsNewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  RepositoriesRepoIdRoute: RepositoriesRepoIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  AppsIndexRoute: AppsIndexRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TerminalsIndexRoute: TerminalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
