import { useState, useEffect, useMemo } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Field, FieldGroup, FieldLabel, FieldDescription } from '@/components/ui/field'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxEmpty,
} from '@/components/ui/combobox'
import { HugeiconsIcon } from '@hugeicons/react'
import { Folder01Icon } from '@hugeicons/core-free-icons'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { useBranches, checkIsGitRepo } from '@/hooks/use-filesystem'
import { useWorktreeBasePath, useDefaultGitReposDir, useDefaultAgent, useOpencodeModel } from '@/hooks/use-config'
import { AGENT_DISPLAY_NAMES, type AgentType } from '@/types'
import { useRepositories } from '@/hooks/use-repositories'
import { useProjects } from '@/hooks/use-projects'
import { FilesystemBrowser } from '@/components/ui/filesystem-browser'
import type { Task } from '@/types'
import { ModelPicker } from '@/components/opencode/model-picker'
import { fetchJSON } from '@/lib/api'
import { useQueryClient } from '@tanstack/react-query'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function generateBranchName(text: string): string {
  const words = text.trim().split(/\s+/).slice(0, 4).join(' ')
  const slug = slugify(words)
  if (!slug) return ''
  const suffix = Math.random().toString(36).substring(2, 6)
  return `${slug}-${suffix}`
}

interface InitializeWorktreeTaskModalProps {
  task: Task
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function InitializeWorktreeTaskModal({ task, open, onOpenChange }: InitializeWorktreeTaskModalProps) {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const [browserOpen, setBrowserOpen] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)

  const [repoPath, setRepoPath] = useState('')
  const [baseBranch, setBaseBranch] = useState('')
  const [branch, setBranch] = useState('')
  const [autoGeneratedBranch, setAutoGeneratedBranch] = useState('')
  const [prefix, setPrefix] = useState('')
  const [aiMode, setAiMode] = useState<'default' | 'plan'>('default')
  const [agent, setAgent] = useState<AgentType>('claude')
  const [selectedRepoId, setSelectedRepoId] = useState<string | null>(null)
  const [repoTab, setRepoTab] = useState<'saved' | 'browse'>('browse')
  const [repoSearchQuery, setRepoSearchQuery] = useState('')
  const [repoError, setRepoError] = useState<string | null>(null)
  const [isValidatingRepo, setIsValidatingRepo] = useState(false)
  const [opencodeModel, setOpencodeModel] = useState<string | null>(null)

  const { data: worktreeBasePath } = useWorktreeBasePath()
  const { data: defaultGitReposDir } = useDefaultGitReposDir()
  const { data: defaultAgent } = useDefaultAgent()
  const { data: globalOpencodeModel } = useOpencodeModel()
  const { data: repositories } = useRepositories()
  const { data: projects } = useProjects()
  const { data: branchData, isLoading: branchesLoading } = useBranches(repoPath || null)

  const selectedRepo = selectedRepoId ? repositories?.find((r) => r.id === selectedRepoId) : null

  // Find the project that contains the selected repository (for config fallback)
  const selectedRepoProject = useMemo(() => {
    if (!selectedRepoId || !projects) return null
    return projects.find((p) => p.repositories.some((r) => r.id === selectedRepoId)) ?? null
  }, [selectedRepoId, projects])

  const filteredRepositories = useMemo(() => {
    if (!repositories) return []
    if (selectedRepo && repoSearchQuery === selectedRepo.displayName) {
      return repositories
    }
    if (!repoSearchQuery.trim()) return repositories
    const query = repoSearchQuery.toLowerCase()
    return repositories.filter((repo) =>
      repo.displayName.toLowerCase().includes(query) ||
      repo.path.toLowerCase().includes(query)
    )
  }, [repositories, repoSearchQuery, selectedRepo])

  // Generate branch name from task title
  useEffect(() => {
    if (open) {
      setAutoGeneratedBranch(generateBranchName(task.title))
      setPrefix(task.prefix || '')
    }
  }, [open, task.title, task.prefix])

  // Set default tab based on whether repositories exist
  useEffect(() => {
    if (repositories && repositories.length > 0) {
      setRepoTab('saved')
    } else {
      setRepoTab('browse')
    }
  }, [repositories])

  // Initialize with first repository when modal opens
  useEffect(() => {
    if (open) {
      const selectedRepo = repositories && repositories.length > 0 ? repositories[0] : null

      // Find the project for this repository (for config fallback)
      const repoProject = selectedRepo && projects
        ? projects.find((p) => p.repositories.some((r) => r.id === selectedRepo.id))
        : null

      // Set agent priority: repo -> project -> global -> 'claude'
      if (selectedRepo?.defaultAgent) {
        setAgent(selectedRepo.defaultAgent)
      } else if (repoProject?.defaultAgent) {
        setAgent(repoProject.defaultAgent)
      } else if (defaultAgent) {
        setAgent(defaultAgent)
      }

      // Set OpenCode model: repo -> project -> global -> null
      if (selectedRepo?.opencodeModel) {
        setOpencodeModel(selectedRepo.opencodeModel)
      } else if (repoProject?.opencodeModel) {
        setOpencodeModel(repoProject.opencodeModel)
      } else if (globalOpencodeModel) {
        setOpencodeModel(globalOpencodeModel)
      } else {
        setOpencodeModel(null)
      }

      if (repositories && repositories.length > 0) {
        const firstRepo = repositories[0]
        setSelectedRepoId(firstRepo.id)
        setRepoPath(firstRepo.path)
        setRepoSearchQuery(firstRepo.displayName)
        setRepoTab('saved')
      }

      // Set AI mode based on task description
      if (task.description?.trim()) {
        setAiMode('plan')
      } else {
        setAiMode('default')
      }
    }
  }, [open, repositories, projects, defaultAgent, globalOpencodeModel, task.description])

  // Set default base branch when branches are loaded
  useEffect(() => {
    if (branchData) {
      const repo = repositories?.find(r => r.id === selectedRepoId)
      const preferred = repo?.lastBaseBranch
      const allBranches = [...branchData.branches, ...(branchData.remoteBranches ?? [])]
      const branch = preferred && allBranches.includes(preferred)
        ? preferred
        : branchData.defaultBranch || branchData.branches[0] || 'main'
      setBaseBranch(branch)
    } else {
      setBaseBranch('')
    }
  }, [branchData, repoPath, repositories, selectedRepoId])

  const handleRepoSelect = async (path: string) => {
    setRepoError(null)
    setIsValidatingRepo(true)

    try {
      const result = await checkIsGitRepo(path)

      if (!result.isGitRepo) {
        setRepoError('Selected folder is not a git repository')
        setIsValidatingRepo(false)
        return
      }

      setRepoPath(path)

      const existingRepo = repositories?.find((r) => r.path === path)
      if (existingRepo) {
        setSelectedRepoId(existingRepo.id)
      } else {
        setSelectedRepoId(null)
      }
    } catch (err) {
      setRepoError(err instanceof Error ? err.message : 'Validation failed')
    } finally {
      setIsValidatingRepo(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!repoPath) return

    setIsSubmitting(true)

    try {
      const repoName = repoPath.split('/').pop() || 'repo'
      const rawBranchForSubmit = branch.trim() || autoGeneratedBranch
      const prefixedBranch = prefix.trim() ? `${prefix.trim().replace(/\/+$/, '')}/${rawBranchForSubmit}` : rawBranchForSubmit
      const worktreePath = `${worktreeBasePath}/${prefixedBranch}`

      // Resolve agent options: repo -> project -> (global is handled by backend)
      const agentOptions = agent === 'claude'
        ? (selectedRepo?.claudeOptions ?? selectedRepoProject?.claudeOptions)
        : (selectedRepo?.opencodeOptions ?? selectedRepoProject?.opencodeOptions)

      // Initialize the task as a worktree task by updating it with git fields
      await fetchJSON<Task>(`/api/tasks/${task.id}/initialize-worktree`, {
        method: 'POST',
        body: JSON.stringify({
          agent,
          aiMode,
          repoPath,
          repoName,
          baseBranch: baseBranch || 'main',
          branch: prefixedBranch,
          prefix: prefix.trim() || undefined,
          worktreePath,
          copyFiles: selectedRepo?.copyFiles || undefined,
          startupScript: [selectedRepoProject?.startupScript, selectedRepo?.startupScript].filter(Boolean).join('\n') || undefined,
          agentOptions: agentOptions || undefined,
          opencodeModel: agent === 'opencode' ? opencodeModel : undefined,
        }),
      })

      // Invalidate queries to refresh task data
      queryClient.invalidateQueries({ queryKey: ['tasks'] })
      queryClient.invalidateQueries({ queryKey: ['tasks', task.id] })

      onOpenChange(false)

      // Navigate to refresh the task view with terminal
      const navState = task.description?.trim()
        ? { aiMode, description: task.description.trim(), focusTerminal: true }
        : { aiMode, focusTerminal: true }
      navigate({
        to: '/tasks/$taskId',
        params: { taskId: task.id },
        state: navState as Record<string, unknown>,
        replace: true,
      })
    } catch (error) {
      toast.error('Failed to initialize worktree task', {
        description: error instanceof Error ? error.message : String(error),
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  const rawBranch = branch.trim() || autoGeneratedBranch
  const effectiveBranch = prefix.trim() && rawBranch ? `${prefix.trim().replace(/\/+$/, '')}/${rawBranch}` : rawBranch
  const displayWorktreePath = effectiveBranch
    ? `${worktreeBasePath}/${effectiveBranch}`
    : ''

  const canSubmit = !isSubmitting && !!repoPath

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-md max-h-[80dvh] flex flex-col overflow-hidden">
          <form onSubmit={handleSubmit} className="flex flex-col min-h-0 flex-1">
            <DialogHeader className="shrink-0">
              <DialogTitle>Initialize as Worktree Task</DialogTitle>
              <DialogDescription>
                Create a git worktree and start a coding session for "{task.title}"
              </DialogDescription>
            </DialogHeader>

            <FieldGroup className="mt-4 pb-4 overflow-y-auto min-h-0 flex-1">
              <Field>
                <FieldLabel>AI Mode</FieldLabel>
                <ToggleGroup
                  value={[aiMode]}
                  onValueChange={(value) => {
                    const selected = Array.isArray(value) ? value[0] : value
                    if (selected) setAiMode(selected as 'default' | 'plan')
                  }}
                  className="w-full"
                  variant="outline"
                >
                  <ToggleGroupItem value="plan" className="flex-1">Plan</ToggleGroupItem>
                  <ToggleGroupItem value="default" className="flex-1">Execute</ToggleGroupItem>
                </ToggleGroup>
              </Field>

              <Field>
                <FieldLabel>Agent</FieldLabel>
                <Select value={agent} onValueChange={(value) => setAgent(value as AgentType)}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(Object.keys(AGENT_DISPLAY_NAMES) as AgentType[]).map((agentType) => (
                      <SelectItem key={agentType} value={agentType}>
                        {AGENT_DISPLAY_NAMES[agentType]}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>

              {agent === 'opencode' && (
                <Field>
                  <FieldLabel>OpenCode Model</FieldLabel>
                  <ModelPicker
                    value={opencodeModel}
                    onChange={setOpencodeModel}
                    placeholder="Select model..."
                  />
                </Field>
              )}

              <Field>
                <FieldLabel>Repository</FieldLabel>
                <Tabs
                  value={repoTab}
                  onValueChange={(v) => {
                    setRepoTab(v as 'saved' | 'browse')
                    setRepoError(null)
                  }}
                >
                  <TabsList>
                    <TabsTrigger value="saved" disabled={!repositories?.length}>
                      Saved
                    </TabsTrigger>
                    <TabsTrigger value="browse">Browse</TabsTrigger>
                  </TabsList>

                  <TabsContent value="saved" className="mt-2">
                    <Combobox
                      value={selectedRepoId || ''}
                      onValueChange={(id) => {
                        const repo = repositories?.find((r) => r.id === id)
                        if (repo) {
                          setSelectedRepoId(id as string)
                          setRepoPath(repo.path)
                          setRepoSearchQuery(repo.displayName)
                          setRepoError(null)
                          if (repo.defaultAgent) {
                            setAgent(repo.defaultAgent)
                          }
                          setOpencodeModel(repo.opencodeModel ?? globalOpencodeModel ?? null)
                        }
                      }}
                      inputValue={repoSearchQuery}
                      onInputValueChange={setRepoSearchQuery}
                      itemToStringLabel={(id) =>
                        repositories?.find((r) => r.id === id)?.displayName || ''
                      }
                    >
                      <ComboboxInput placeholder="Search repositories..." className="w-full" />
                      <ComboboxContent>
                        <ComboboxList>
                          <ComboboxEmpty>No repositories found</ComboboxEmpty>
                          {filteredRepositories.map((repo) => (
                            <ComboboxItem key={repo.id} value={repo.id}>
                              {repo.displayName}
                            </ComboboxItem>
                          ))}
                        </ComboboxList>
                      </ComboboxContent>
                    </Combobox>
                  </TabsContent>

                  <TabsContent value="browse" className="mt-2">
                    <Button
                      type="button"
                      variant="outline"
                      className="w-full justify-start font-normal"
                      onClick={() => setBrowserOpen(true)}
                      disabled={isValidatingRepo}
                    >
                      <HugeiconsIcon icon={Folder01Icon} size={14} strokeWidth={2} className="mr-2" />
                      {isValidatingRepo ? (
                        <span className="text-muted-foreground">Validating...</span>
                      ) : repoPath && !selectedRepoId ? (
                        <span className="truncate">{repoPath}</span>
                      ) : (
                        <span className="text-muted-foreground">Select folder...</span>
                      )}
                    </Button>
                  </TabsContent>
                </Tabs>

                {repoError && (
                  <p className="text-sm text-destructive">{repoError}</p>
                )}

                {repoPath && !repoError && (
                  <FieldDescription className="font-mono text-xs truncate">
                    {repoPath}
                  </FieldDescription>
                )}
              </Field>

              <Field>
                <FieldLabel>Base Branch</FieldLabel>
                <Select
                  value={baseBranch}
                  onValueChange={(value) => setBaseBranch(value ?? '')}
                  disabled={!repoPath || branchesLoading}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue>
                      {baseBranch || (
                        <span className="text-muted-foreground">
                          {!repoPath
                            ? 'Select repository first'
                            : branchesLoading
                            ? 'Loading branches...'
                            : 'Select branch'}
                        </span>
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {branchData?.branches && branchData.branches.length > 0 && (
                      <SelectGroup>
                        {(branchData.remoteBranches?.length ?? 0) > 0 && <SelectLabel>Local</SelectLabel>}
                        {branchData.branches.map((b) => (
                          <SelectItem key={b} value={b}>
                            {b}
                            {b === branchData.current && (
                              <span className="text-muted-foreground ml-2">(current)</span>
                            )}
                          </SelectItem>
                        ))}
                      </SelectGroup>
                    )}
                    {(branchData?.remoteBranches?.length ?? 0) > 0 && (
                      <SelectGroup>
                        <SelectLabel>Remote</SelectLabel>
                        {branchData!.remoteBranches.map((b) => (
                          <SelectItem key={b} value={b}>
                            {b}
                          </SelectItem>
                        ))}
                      </SelectGroup>
                    )}
                  </SelectContent>
                </Select>
              </Field>

              <Field>
                <FieldLabel>Branch Name</FieldLabel>
                <Input
                  value={branch}
                  onChange={(e) => setBranch(e.target.value)}
                  placeholder={autoGeneratedBranch || 'Enter branch name'}
                />
                {displayWorktreePath && (
                  <FieldDescription>
                    Worktree: {displayWorktreePath}
                  </FieldDescription>
                )}
                {!branch.trim() && autoGeneratedBranch && (
                  <FieldDescription>
                    Auto-generated: {autoGeneratedBranch}
                  </FieldDescription>
                )}
              </Field>
            </FieldGroup>

            <DialogFooter className="mt-4 shrink-0">
              <DialogClose render={<Button variant="outline" type="button" />}>
                Cancel
              </DialogClose>
              <Button type="submit" disabled={!canSubmit}>
                {isSubmitting ? 'Initializing...' : 'Initialize & Open'}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <FilesystemBrowser
        open={browserOpen}
        onOpenChange={setBrowserOpen}
        onSelect={handleRepoSelect}
        initialPath={defaultGitReposDir || undefined}
      />
    </>
  )
}
