// Single source of truth for config keys used by both frontend and backend.
// Both frontend/hooks/use-config.ts and server/routes/config.ts import from here.
export const CONFIG_KEYS = {
  PORT: 'server.port',
  WORKTREE_BASE_PATH: 'worktree_base_path', // Read-only, derived from FULCRUM_DIR
  SCRATCH_BASE_PATH: 'scratch_base_path', // Read-only, derived from FULCRUM_DIR
  HOME_DIR: 'home_dir', // Read-only, system home directory
  DEFAULT_GIT_REPOS_DIR: 'paths.defaultGitReposDir',
  REMOTE_HOST: 'remoteFulcrum.host',
  REMOTE_PORT: 'remoteFulcrum.port',
  EDITOR_APP: 'editor.app',
  EDITOR_HOST: 'editor.host',
  EDITOR_SSH_PORT: 'editor.sshPort',
  GITHUB_PAT: 'integrations.githubPat',
  GOOGLE_CLIENT_ID: 'integrations.googleClientId',
  GOOGLE_CLIENT_SECRET: 'integrations.googleClientSecret',
  DEFAULT_AGENT: 'agent.defaultAgent',
  OPENCODE_MODEL: 'agent.opencodeModel',
  OPENCODE_DEFAULT_AGENT: 'agent.opencodeDefaultAgent',
  OPENCODE_PLAN_AGENT: 'agent.opencodePlanAgent',
  AGENT_AUTO_SCROLL_TO_BOTTOM: 'agent.autoScrollToBottom',
  CLAUDE_CODE_PATH: 'agent.claudeCodePath',
  LANGUAGE: 'appearance.language',
  THEME: 'appearance.theme',
  TIMEZONE: 'appearance.timezone',
  SYNC_CLAUDE_CODE_THEME: 'appearance.syncClaudeCodeTheme',
  CLAUDE_CODE_LIGHT_THEME: 'appearance.claudeCodeLightTheme',
  CLAUDE_CODE_DARK_THEME: 'appearance.claudeCodeDarkTheme',
  DEFAULT_TASK_TYPE: 'tasks.defaultTaskType',
  START_WORKTREE_TASKS_IMMEDIATELY: 'tasks.startWorktreeTasksImmediately',
  SCRATCH_STARTUP_SCRIPT: 'tasks.scratchStartupScript',
  ASSISTANT_PROVIDER: 'assistant.provider',
  ASSISTANT_MODEL: 'assistant.model',
  ASSISTANT_OBSERVER_MODEL: 'assistant.observerModel',
  ASSISTANT_OBSERVER_PROVIDER: 'assistant.observerProvider',
  ASSISTANT_OBSERVER_OPENCODE_MODEL: 'assistant.observerOpencodeModel',
  ASSISTANT_CUSTOM_INSTRUCTIONS: 'assistant.customInstructions',
  ASSISTANT_DOCUMENTS_DIR: 'assistant.documentsDir',
  ASSISTANT_RITUALS_ENABLED: 'assistant.ritualsEnabled',
  ASSISTANT_MORNING_RITUAL_TIME: 'assistant.morningRitual.time',
  ASSISTANT_MORNING_RITUAL_PROMPT: 'assistant.morningRitual.prompt',
  ASSISTANT_EVENING_RITUAL_TIME: 'assistant.eveningRitual.time',
  ASSISTANT_EVENING_RITUAL_PROMPT: 'assistant.eveningRitual.prompt',
  EMAIL_POLL_INTERVAL: 'channels.email.pollIntervalSeconds',
  CALDAV_ENABLED: 'caldav.enabled',
  CALDAV_SERVER_URL: 'caldav.serverUrl',
  CALDAV_USERNAME: 'caldav.username',
  CALDAV_PASSWORD: 'caldav.password',
  CALDAV_SYNC_INTERVAL: 'caldav.syncIntervalMinutes',
  CALDAV_AUTH_TYPE: 'caldav.authType',
  CALDAV_GOOGLE_CLIENT_ID: 'caldav.googleClientId',
  CALDAV_GOOGLE_CLIENT_SECRET: 'caldav.googleClientSecret',
  CALDAV_OAUTH_TOKENS: 'caldav.oauthTokens',
} as const

export type ConfigKey = (typeof CONFIG_KEYS)[keyof typeof CONFIG_KEYS]
